services:
  app:
    build: .
    environment:
    depends_on:
      db:
        condition: service_healthy
    networks:


  db:
    image:
    restart: always
    environment:
    volumes:
    healthcheck:
    ports:
    networks:


volumes:

networks:
