services:
  app:
    build: .
    environment:
      DB_HOST:
      DB_USER:
      DB_PASSWORD:
      DB_NAME:
      DB_PORT:
    depends_on:
      db:
        condition: service_healthy
    networks:


  db:
    image:
    restart: always
    environment:
    volumes:
      - ./db/init:/docker-entrypoing-initdb.d
    healthcheck:
      test: []
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 1s
    ports:
    networks:


volumes:

networks:
