services:
  app:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST:
      DB_USER:
      DB_PASSWORD:
      DB_NAME:
      DB_PORT:
    depends_on:
      db:
        condition: service_healthy
    networks:


  db:
    image:
    restart: always
    environment:
    volumes:
      - db_data:/var/lib/unknown_sql/data
    healthcheck:
      test: []
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 1s
    ports:
    networks:


  migrate:
    image: migrate:migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./db/migrations:/db/migrations
    environment:
    command: [ "-path", "/db/migrations", "-database", "driver://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable", "up" ]
    networks:
      bittersweet:


volumes:
  db_data:


networks:
